### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by alroy2023** [Souhailkudo/VTM_intra_CNN_LGBM_patch#2]
Hello,  could you upload the dataset?  It will help me a lot, thank you very much！

**Comment by balbalabal** [comment]
hey, bro, Did you get the data set? Can you send it to me? I really need it. Thank you very much

**Comment by alroy2023** [comment]
> hey, bro, Did you get the data set? Can you send it to me? I really need it. Thank you very much

I haven't got the dataset either, so I can't help you, bro
